dofile("tests/mission-demand/test_mission_demand.lua")
dofile("tests/mission-demand/test_resource_demand_policy.lua")
dofile("tests/mission-demand/test_resource_demand_coordinator.lua")
dofile("tests/mission-demand/test_fob_attack_demand_policy.lua")
dofile("tests/mission-demand/test_fob_threat_opszone_adapter.lua")
dofile("tests/mission-demand/test_ground_installation_alarm_evidence_adapter.lua")
dofile("tests/mission-demand/test_fob_attack_cas_dispatch_adapter.lua")
dofile("tests/mission-demand/test_fob_attack_fire_support.lua")
dofile("tests/mission-demand/test_fob_attack_functional_arty.lua")
dofile("tests/mission-demand/test_ground_ammo_resupply_executor.lua")
dofile("tests/mission-demand/test_ground_personnel_deployment_ledger.lua")
dofile("tests/mission-demand/test_helicopter_flightpath_corridor.lua")

print("PASS mission-demand test suite")
