dofile("tests/mission-demand/test_mission_demand.lua")
dofile("tests/mission-demand/test_resource_demand_policy.lua")
dofile("tests/mission-demand/test_ground_resource_normalization.lua")
dofile("tests/mission-demand/test_ground_ammo_rearm_adapter.lua")
print("PASS mission-demand domain contract suite")
