[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$registrationSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\05-kandahar-dual-airwing-registration-preflight.lua'
$parkingSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\06-kandahar-dual-airwing-parking-contract-preflight.lua'
$uavParkingSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\10-kandahar-uav-fixed-parking-contract.lua'
$uavAssetSyncSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\10b-kandahar-uav-registered-asset-parking-sync.lua'
$foundationSource = Join-Path $repoRoot 'mission\air-operations\kandahar\src\01-kandahar-foundation-start.lua'
$outputDir = Join-Path $repoRoot 'mission\air-operations\dist'
$outputFile = Join-Path $outputDir 'OMW_AIROPS_KANDAHAR.lua'

$sources = @(
    $registrationSource,
    $parkingSource,
    $uavParkingSource,
    $uavAssetSyncSource,
    $foundationSource
)

foreach ($path in $sources) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required source file not found: $path"
    }
}

$sourceTexts = [System.Collections.Generic.List[string]]::new()
foreach ($source in $sources) {
    $text = Get-Content -LiteralPath $source -Raw
    if ([string]::IsNullOrWhiteSpace($text)) {
        throw "Required source file is empty: $source"
    }
    $sourceTexts.Add($text)
}

$foundationText = Get-Content -LiteralPath $foundationSource -Raw
$combinedText = [string]::Join("`n", $sourceTexts.ToArray())

$requiredTokens = @(
    'AW_US_KAF_451_AEW',
    'AW_US_KAF_159_CAB_TF_THUNDER',
    'SQ_US_KAF_A10C_74_EFS',
    'SQ_US_KAF_HH60G_26_ERQS',
    'SQ_US_KAF_C130_772_EAS',
    'SQ_US_KAF_MQ1_361_ERS',
    'SQ_US_KAF_MQ9_361_ERS',
    'SQ_US_KAF_AH64_4_227_AVN',
    'SQ_US_KAF_OH58D_7_17_CAV',
    'SQ_US_KAF_CH47_7_101_GSAB',
    'SQ_US_KAF_UH60_7_101_GSAB',
    'KandaharRegistrationPreflight',
    'KandaharParkingContractPreflight',
    'KandaharUAVParkingContract',
    'KandaharUAVAssetParkingSync',
    'OMW.AirOps.Kandahar = foundation',
    'READY_NO_TASKING',
    'uavFinalParkingRestricted=false'
)

foreach ($token in $requiredTokens) {
    if ($combinedText.IndexOf($token, [System.StringComparison]::Ordinal) -lt 0) {
        throw "Kandahar AirOps source missing required token: $token"
    }
}

$forbiddenTokens = @(
    'AUFTRAG:New',
    'OPSTRANSPORT:New',
    'COMMANDER:New',
    'CHIEF:New',
    ':AddMission(',
    ':NewPayload(',
    ':AddRequest(',
    'WAREHOUSE.Descriptor.GROUPNAME',
    'SPAWN:New',
    'SetDespawnAfterLanding(false)',
    'OnAfterElementTakeoff',
    'OnAfterElementLanded',
    'OnAfterElementArrived'
)

foreach ($token in $forbiddenTokens) {
    if ($combinedText.IndexOf($token, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "Normalized Kandahar AirOps bundle contains forbidden task/test token: $token"
    }
}

if ($foundationText.IndexOf(':Start()', [System.StringComparison]::Ordinal) -lt 0) {
    throw 'Foundation source does not start AIRWING instances.'
}

$parts = [System.Collections.Generic.List[string]]::new()
$parts.Add('-- Operation Mountain Watch - normalized Kandahar AirOps foundation')
$parts.Add('-- Generated by tools/build-omw-airops-kandahar.ps1')
$parts.Add('-- BuilderVersion: OMW-AIROPS-KANDAHAR-FOUNDATION-2')
$parts.Add('-- Scope: two AIRWINGs, nine SQUADRONs, parking contracts and UAV initial-spawn pools')
$parts.Add('-- No AUFTRAG, payload, transport, commander or direct-spawn logic is included.')
$parts.Add('-- Known limitation: DCS native post-landing UAV stand selection is not type-pool constrained.')
foreach ($sourceText in $sourceTexts) {
    $parts.Add($sourceText)
}

New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
$bundle = [string]::Join("`r`n`r`n", $parts.ToArray())

$assemblyCorruptionTokens = @(
    'System.Object[]',
    'System.String[]',
    'System.Collections.Generic.List'
)
foreach ($token in $assemblyCorruptionTokens) {
    if ($bundle.IndexOf($token, [System.StringComparison]::Ordinal) -ge 0) {
        throw "Generated bundle contains PowerShell object-string corruption token: $token"
    }
}

foreach ($token in $requiredTokens) {
    if ($bundle.IndexOf($token, [System.StringComparison]::Ordinal) -lt 0) {
        throw "Generated bundle missing required token after assembly: $token"
    }
}

[System.IO.File]::WriteAllText($outputFile, $bundle, [System.Text.UTF8Encoding]::new($false))

$writtenText = Get-Content -LiteralPath $outputFile -Raw
if ($writtenText -ne $bundle) {
    throw "Generated file verification failed: written content differs from assembled bundle: $outputFile"
}

$luac = Get-Command luac -ErrorAction SilentlyContinue
if ($luac) {
    & $luac.Source -p $outputFile
    if ($LASTEXITCODE -ne 0) {
        throw "luac syntax validation failed for $outputFile"
    }
    Write-Host 'LuaSyntax: PASS'
}
else {
    Write-Host 'LuaSyntax: SKIPPED (luac not installed)'
}

Write-Host 'BuilderVersion: OMW-AIROPS-KANDAHAR-FOUNDATION-2'
Write-Host "Output: $outputFile"
Write-Host 'Assembly: PASS (explicit string list; no nested PowerShell object arrays)'
Write-Host 'AIRWINGs: 2'
Write-Host 'SQUADRONs: 9'
Write-Host 'RegisteredPhysicalAirframes: 112'
Write-Host 'DeferredMC12: 6'
Write-Host 'Parking: Main and Heliport safe-parking contracts'
Write-Host 'UAVInitialSpawnPools: MQ-1 G01-G08; MQ-9 G09-G11; runtime filtered'
Write-Host 'Tasking: NONE'
Write-Host 'Payloads: NONE'
Write-Host 'Transport: NONE'
Write-Host 'Commander: NONE'
Write-Host 'DirectSpawnRequests: NONE'
Write-Host 'KnownLimitation: post-landing UAV final stand remains DCS-native and not type-pool constrained'
