[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$registrationSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\05-kandahar-dual-airwing-registration-preflight.lua'
$parkingSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\06-kandahar-dual-airwing-parking-contract-preflight.lua'
$uavContractSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\10-kandahar-uav-fixed-parking-contract.lua'
$uavAssetSyncSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\10b-kandahar-uav-registered-asset-parking-sync.lua'
$returnParkingSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\12-kandahar-uav-return-parking-test.lua'
$outputDir = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\dist'
$outputFile = Join-Path $outputDir 'OMW_AirOps_Kandahar_UAV_Return_Parking.lua'

foreach ($path in @($registrationSource, $parkingSource, $uavContractSource, $uavAssetSyncSource, $returnParkingSource)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required source file not found: $path"
    }
}

$testText = Get-Content -LiteralPath $returnParkingSource -Raw
$combinedText = @(
    (Get-Content -LiteralPath $uavContractSource -Raw),
    (Get-Content -LiteralPath $uavAssetSyncSource -Raw),
    $testText
) -join "`n"

$requiredTokens = @(
    'SQ_US_KAF_MQ1_361_ERS',
    'SQ_US_KAF_MQ9_361_ERS',
    'TPL_AIR_US_KAF_MQ1A_RECON_1SHIP',
    'TPL_AIR_US_KAF_MQ9_RECON_1SHIP',
    'asset.parkingIDs',
    'registeredAssetsSynchronized=true',
    'AUFTRAG:NewORBIT(',
    ':AddMission(',
    ':AssignSquadrons(',
    ':AddRequiredPayload(',
    ':NewPayload(',
    ':SetDuration(',
    ':SetDespawnAfterLanding(false)',
    'OnAfterElementEngineOn',
    'OnAfterElementTaxiing',
    'OnAfterElementTakeoff',
    'OnAfterElementAirborne',
    'OnAfterElementLanded',
    'OnAfterElementParking',
    'OnAfterElementArrived',
    'FINAL_PARKING_OUTSIDE_TYPE_POOL',
    'warehouseReturnNotClaimed=true'
)

foreach ($token in $requiredTokens) {
    if ($combinedText.IndexOf($token, [System.StringComparison]::Ordinal) -lt 0) {
        throw "UAV return-parking source missing required token: $token"
    }
}

$forbiddenTokens = @(
    'SPAWN:New',
    'OPSTRANSPORT:New',
    'COMMANDER:New',
    'CHIEF:New',
    ':AddRequest(',
    'WAREHOUSE.Descriptor.GROUPNAME',
    'SetAllowSpawnOnClientParking',
    'TaskRoute',
    'RouteTo',
    'CommandStart'
)

foreach ($token in $forbiddenTokens) {
    if ($testText.IndexOf($token, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "UAV return-parking source contains forbidden direct-control token: $token"
    }
}

$parts = @(
    '-- Generated by tools/build-kandahar-uav-return-parking.ps1',
    '-- BuilderVersion: KAF-UAV-RETURN-PARKING-1',
    '-- RuntimeBoundary: AIRWING/AUFTRAG full-cycle MQ-1 and MQ-9 return/final-parking observation',
    (Get-Content -LiteralPath $registrationSource -Raw),
    (Get-Content -LiteralPath $parkingSource -Raw),
    (Get-Content -LiteralPath $uavContractSource -Raw),
    (Get-Content -LiteralPath $uavAssetSyncSource -Raw),
    $testText
)

New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
$bundle = [string]::Join("`r`n`r`n", $parts)
[System.IO.File]::WriteAllText($outputFile, $bundle, [System.Text.UTF8Encoding]::new($false))

$luac = Get-Command luac -ErrorAction SilentlyContinue
if ($luac) {
    & $luac.Source -p $outputFile
    if ($LASTEXITCODE -ne 0) {
        throw "luac syntax validation failed for $outputFile"
    }
    Write-Host 'LuaSyntax: PASS'
}
else {
    Write-Host 'LuaSyntax: SKIPPED (luac not installed)'
}

Write-Host 'BuilderVersion: KAF-UAV-RETURN-PARKING-1'
Write-Host "Output: $outputFile"
Write-Host 'Missions: 2 x AUFTRAG ORBIT'
Write-Host 'MQ1Pool: runtime-filtered G01-G08'
Write-Host 'MQ9Pool: runtime-filtered G09-G11'
Write-Host 'MissionDurationSeconds: 180'
Write-Host 'MissionStaggerSeconds: 45'
Write-Host 'OverallTimeoutSeconds: 2400'
Write-Host 'PayloadSource: approved operational UAV templates'
Write-Host 'DespawnAfterLanding: false'
Write-Host 'WarehouseReturnAcceptance: deferred'
Write-Host 'RuntimeBoundary: engine start, taxi-out, takeoff, orbit, RTB, landing, taxi-in and final parking; no direct SPAWN/self-request/route command'
