[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$versionPath = Join-Path $repositoryRoot "vendor/moose/VERSION.md"
$moosePath = Join-Path $repositoryRoot "vendor/moose/Moose.lua"
$configPath = Join-Path $repositoryRoot "mission/tests/tm01-blue-convoy/config-tm01m.lua"
$sourcePath = Join-Path $repositoryRoot "mission/tests/tm01-blue-convoy/src/tm01m.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm01-blue-convoy/dist/TM01M.lua"

function Get-MetadataValue {
  param(
    [Parameter(Mandatory = $true)][string]$Content,
    [Parameter(Mandatory = $true)][string]$Pattern,
    [Parameter(Mandatory = $true)][string]$Description
  )
  $match = [regex]::Match($Content, $Pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
  if (-not $match.Success) { throw "Could not read $Description." }
  return $match.Groups[1].Value.Trim()
}

function Get-NormalizedSource {
  param([Parameter(Mandatory = $true)][string]$Path)
  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

$versionContent = [System.IO.File]::ReadAllText($versionPath)
$expectedMooseVersion = Get-MetadataValue -Content $versionContent -Pattern '^Version:\s*(\S+)\s*$' -Description "MOOSE version"
$expectedHash = (Get-MetadataValue -Content $versionContent -Pattern '^SHA-256 Moose\.lua:\s*([0-9a-fA-F]{64})\s*$' -Description "expected Moose.lua SHA-256").ToLowerInvariant()
$actualHash = (Get-FileHash -LiteralPath $moosePath -Algorithm SHA256).Hash.ToLowerInvariant()
if ($actualHash -cne $expectedHash) {
  throw "MOOSE SHA-256 mismatch. Expected $expectedHash but found $actualHash."
}

$configContent = [System.IO.File]::ReadAllText($configPath)
$configurationVersion = Get-MetadataValue -Content $configContent -Pattern '^\s*configurationVersion\s*=\s*"([^"]+)"\s*,' -Description "TM01M configuration version"
$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm01m-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- Load vendor/moose/Moose.lua before this bundle.")
[void]$builder.AppendLine("local OMWBuild = {")
[void]$builder.AppendLine('  testId = "TM01",')
[void]$builder.AppendLine('  stageId = "TM01M",')
[void]$builder.AppendLine(('  configurationVersion = "{0}",' -f $configurationVersion))
[void]$builder.AppendLine(('  expectedMooseVersion = "{0}",' -f $expectedMooseVersion))
[void]$builder.AppendLine(('  expectedMooseFileSha256 = "{0}",' -f $expectedHash))
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine("}")
[void]$builder.AppendLine()
[void]$builder.AppendLine("local TM01MConfig = (function()")
[void]$builder.AppendLine((Get-NormalizedSource -Path $configPath))
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine()
[void]$builder.AppendLine("local TM01M = (function()")
[void]$builder.AppendLine((Get-NormalizedSource -Path $sourcePath))
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine()
[void]$builder.AppendLine("local entryOk, entryResult = pcall(function()")
[void]$builder.AppendLine("  return TM01M.start({ build = OMWBuild, config = TM01MConfig })")
[void]$builder.AppendLine("end)")
[void]$builder.AppendLine("if not entryOk then")
[void]$builder.AppendLine('  env.error("[OMW][TM01M] bootstrap_uncaught_error " .. tostring(entryResult))')
[void]$builder.AppendLine("end")
[void]$builder.AppendLine("TM01MState = entryOk and entryResult or { outcome = 'FAIL_SCRIPT', detail = tostring(entryResult) }")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)

Write-Output "Verified Moose.lua SHA-256: $actualHash"
Write-Output "Built TM01M bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
