[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $repoRoot 'mission/tests/uav-isr-request/dist'
$output = Join-Path $outDir 'OMW_UAV_ISR_Request_Acceptance_3.lua'

$sources = @(
  'scripts/campaign/OMW_CampaignState.lua',
  'scripts/campaign/OMW_ISR_RequestCoordinator.lua',
  'scripts/campaign/OMW_ISR_UavCampaignStateAdapter.lua',
  'scripts/air-operations/OMW_ISR_RequestMenu.lua',
  'scripts/air-operations/OMW_ISR_UavDispatcher.lua',
  'mission/tests/uav-isr-request/src/03-uav-isr-request-acceptance-3.lua'
)

$forbidden = @(
  '(?i)\bSPAWN\s*:', '(?i)\bmist\.', '(?i)world\.addEventHandler',
  '(?i)trigger\.action', '(?i)coalition\.add(Group|StaticObject)',
  '(?i)Group\.getByName', '(?i)Unit\.getByName', '(?i)missionCommands\.'
)

$parts = New-Object System.Collections.Generic.List[string]
$parts.Add('-- Generated by tools/build-uav-isr-request-acceptance-3.ps1')
$parts.Add('-- Acceptance only: separate MIZ copy; no mutation of production mission.')
$parts.Add('OMW = OMW or {}')
foreach ($relative in $sources) {
  $full = Join-Path $repoRoot $relative
  if (-not (Test-Path -LiteralPath $full)) { throw "Missing source: $relative" }
  $content = [System.IO.File]::ReadAllText($full)
  foreach ($pattern in $forbidden) {
    if ($content -match $pattern) { throw "Forbidden native dispatch API in $relative : $pattern" }
  }
  $name = switch -Wildcard ($relative) {
    '*OMW_CampaignState.lua' { 'CampaignState' }
    '*OMW_ISR_RequestCoordinator.lua' { 'RequestCoordinator' }
    '*OMW_ISR_UavCampaignStateAdapter.lua' { 'UavCampaignStateAdapter' }
    '*OMW_ISR_RequestMenu.lua' { 'RequestMenu' }
    '*OMW_ISR_UavDispatcher.lua' { 'UavDispatcher' }
    '*03-uav-isr-request-acceptance-3.lua' { 'Acceptance' }
    default { throw "No bundle alias for $relative" }
  }
  $parts.Add(('local ' + $name + ' = (function()' + [Environment]::NewLine + $content + [Environment]::NewLine + 'end)()'))
}
$parts.Add('Acceptance.StartWhenKandaharReady()')
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$separator = [Environment]::NewLine + [Environment]::NewLine
[System.IO.File]::WriteAllText($output, ($parts -join $separator) + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $output).Hash.ToLowerInvariant()
Write-Output 'BuilderVersion: OMW-UAV-ISR-REQUEST-ACCEPTANCE-3-13'
Write-Output "Output: $output"
Write-Output "Bundle SHA-256: $hash"
Write-Output 'MIZ mutation: false'
Write-Output 'Physical UAV dispatch: MOOSE AIRWING/AUFTRAG only'
Write-Output 'On-station path: MOOSE AUFTRAG:NewORBIT_CIRCLE'
Write-Output 'On-station contract: 2700 seconds after MOOSE Executing event'
Write-Output 'CampaignState reservation: acceptance-local Kandahar MQ-9'
Write-Output 'Acceptance-only submit radius: 50000 meters'
