[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repositoryRoot "mission/tests/tm02-red-relay/config-tm02v.lua"
$adapterPath = Join-Path $repositoryRoot "mission/tests/tm02-red-relay/src/tm02v-leader-proxy-adapter.lua"
$sourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-relay/src/tm02v.lua"
$diagnosticsPath = Join-Path $repositoryRoot "mission/tests/tm02-red-relay/src/tm02v-bootstrap-diagnostics.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm02-red-relay/dist/TM02V.lua"

function Get-NormalizedSource {
  param([Parameter(Mandatory = $true)][string]$Path)
  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

$configContent = Get-NormalizedSource -Path $configPath
$adapterContent = Get-NormalizedSource -Path $adapterPath
$sourceContent = Get-NormalizedSource -Path $sourcePath
$diagnosticsContent = Get-NormalizedSource -Path $diagnosticsPath
$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm02v-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- Load vendor/moose/Moose.lua before this bundle.")
[void]$builder.AppendLine("local TM02VBuild = {")
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine('  stageId = "TM02V",')
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("local TM02VConfig = (function()")
[void]$builder.AppendLine($configContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02VLeaderProxyAdapter = (function()")
[void]$builder.AppendLine($adapterContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02V = (function()")
[void]$builder.AppendLine($sourceContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02VDiagnostics = (function()")
[void]$builder.AppendLine($diagnosticsContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local ok, result = pcall(function()")
[void]$builder.AppendLine("  TM02VLeaderProxyAdapter.install(TM02VConfig)")
[void]$builder.AppendLine("  return TM02V.start(TM02VConfig, TM02VBuild)")
[void]$builder.AppendLine("end)")
[void]$builder.AppendLine("if not ok then")
[void]$builder.AppendLine('  env.info("[OMW][TM02V] level=ERROR event=bootstrap_uncaught_error reason=" .. tostring(result))')
[void]$builder.AppendLine('elseif type(result) == "table" and result.failed == true then')
[void]$builder.AppendLine("  local diagnosticsOk, diagnosticsError = pcall(function()")
[void]$builder.AppendLine("    result.diagnosticMenu = TM02VDiagnostics.install(TM02VConfig, result)")
[void]$builder.AppendLine("  end)")
[void]$builder.AppendLine("  if not diagnosticsOk then")
[void]$builder.AppendLine('    env.info("[OMW][TM02V] level=ERROR event=diagnostic_menu_failed reason=" .. tostring(diagnosticsError))')
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("end")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)
Write-Output "Built TM02V bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
