[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$registrationSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\05-kandahar-dual-airwing-registration-preflight.lua'
$parkingSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\06-kandahar-dual-airwing-parking-contract-preflight.lua'
$matrixPayload = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\08-kandahar-controlled-parking-matrix.lua.gz.b64'
$outputDir = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\dist'
$outputFile = Join-Path $outputDir 'OMW_AirOps_Kandahar_ControlledParking_Matrix.lua'

foreach ($path in @($registrationSource, $parkingSource, $matrixPayload)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required source file not found: $path"
    }
}

$payloadText = (Get-Content -LiteralPath $matrixPayload -Raw).Trim()
$compressedBytes = [Convert]::FromBase64String($payloadText)
$inputStream = [System.IO.MemoryStream]::new($compressedBytes)
$gzipStream = [System.IO.Compression.GZipStream]::new(
    $inputStream,
    [System.IO.Compression.CompressionMode]::Decompress
)
$reader = [System.IO.StreamReader]::new($gzipStream, [System.Text.Encoding]::UTF8)
try {
    $matrixSource = $reader.ReadToEnd()
}
finally {
    $reader.Dispose()
    $gzipStream.Dispose()
    $inputStream.Dispose()
}

$requiredTokens = @(
    'ControlledParkingMatrix',
    'WAREHOUSE.Descriptor.GROUPNAME',
    ':AddRequest(',
    ':SetParkingIDs(',
    ':SetTakeoffCold(',
    ':Start(',
    'PARKING_IDS_UPDATED',
    'DUPLICATE_TERMINAL_IN_MATRIX',
    'PREVIOUS_GROUP_NOT_RETAINED',
    'CASE_RESULT:',
    'STATIC_CLEARANCE_FAILED',
    'dynamicParkingReservation=true',
    'RESULT: %s cases=%d passed=%d failed=%d'
)
foreach ($token in $requiredTokens) {
    if ($matrixSource.IndexOf($token, [System.StringComparison]::Ordinal) -lt 0) {
        throw "Matrix source missing required token: $token"
    }
}

$forbiddenTokens = @(
    'AUFTRAG:New',
    'OPSTRANSPORT:New',
    'COMMANDER:New',
    'CHIEF:New',
    'NewPayload',
    'SetAllowSpawnOnClientParking'
)
foreach ($token in $forbiddenTokens) {
    if ($matrixSource.IndexOf($token, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "Matrix source contains forbidden constructor or mutation token: $token"
    }
}

$parts = @(
    "-- Generated by tools/build-kandahar-controlled-parking-matrix.ps1",
    "-- BuilderVersion: KAF-CONTROLLED-PARKING-MATRIX-2",
    "-- RuntimeBoundary: two AIRWING starts, nine sequential self-requests, native dynamic parking-ID reservation, cold/uncontrolled parking only",
    (Get-Content -LiteralPath $registrationSource -Raw),
    (Get-Content -LiteralPath $parkingSource -Raw),
    $matrixSource
)

New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
$bundle = [string]::Join("`r`n`r`n", $parts)
[System.IO.File]::WriteAllText($outputFile, $bundle, [System.Text.UTF8Encoding]::new($false))

Write-Host "BuilderVersion: KAF-CONTROLLED-PARKING-MATRIX-2"
Write-Host "Output: $outputFile"
Write-Host "Cases: 9"
Write-Host "ExpectedAssetGroups: 9"
Write-Host "ExpectedUnits: 12"
Write-Host "PreflightGuard: PASS"
Write-Host "DynamicParkingReservation: AIRWING:SetParkingIDs"
Write-Host "RuntimeBoundary: both AIRWINGs started; nine sequential self-requests; cold and uncontrolled; no AUFTRAG/OPSTRANSPORT/payload mutation"
