[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repositoryRoot "mission/tests/tm02-red-relay/config-tm02r.lua"
$sourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-relay/src/tm02r.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm02-red-relay/dist/TM02R.lua"

function Get-NormalizedSource {
  param([Parameter(Mandatory = $true)][string]$Path)
  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

$configContent = Get-NormalizedSource -Path $configPath
$sourceContent = Get-NormalizedSource -Path $sourcePath
$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm02r-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- Load vendor/moose/Moose.lua before this bundle.")
[void]$builder.AppendLine("local TM02RBuild = {")
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine('  stageId = "TM02R",')
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("local TM02RConfig = (function()")
[void]$builder.AppendLine($configContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02R = (function()")
[void]$builder.AppendLine($sourceContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local ok, result = pcall(function() return TM02R.start(TM02RConfig, TM02RBuild) end)")
[void]$builder.AppendLine("if not ok then")
[void]$builder.AppendLine('  env.info("[OMW][TM02R] level=ERROR event=bootstrap_uncaught_error reason=" .. tostring(result))')
[void]$builder.AppendLine("end")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)
Write-Output "Built TM02R bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
