[CmdletBinding()]
param(
  [Parameter(Mandatory = $false)]
  [string]$TownsFile
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repositoryRoot "mission/tests/towns-discovery/config.lua"
$sourcePath = Join-Path $repositoryRoot "src/dev/world-data/towns_discovery.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/towns-discovery/dist/OMW_TOWNS_DISCOVERY.lua"

function Get-NormalizedSource {
  param([Parameter(Mandatory = $true)][string]$Path)

  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
    throw "Required source file not found: $Path"
  }

  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

function ConvertTo-LuaLongString {
  param([Parameter(Mandatory = $true)][string]$Value)

  if ($Value.Contains("]]")) {
    throw "The value cannot be represented as a Lua long string because it contains ]]: $Value"
  }

  return "[[${Value}]]"
}

$configSource = Get-NormalizedSource -Path $configPath
$discoverySource = Get-NormalizedSource -Path $sourcePath
$buildTimestamp = [DateTime]::UtcNow.ToString(
  "yyyy-MM-ddTHH:mm:ssZ",
  [Globalization.CultureInfo]::InvariantCulture
)

$gitCommit = "unknown"
try {
  $resolvedCommit = (& git -C $repositoryRoot rev-parse HEAD 2>$null)
  if ($LASTEXITCODE -eq 0 -and $resolvedCommit) {
    $gitCommit = $resolvedCommit.Trim()
  }
} catch {
  $gitCommit = "unknown"
}

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-towns-discovery-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- Load vendor/moose/Moose.lua before this bundle.")
[void]$builder.AppendLine("-- Source configuration: mission/tests/towns-discovery/config.lua")
[void]$builder.AppendLine("-- Source implementation: src/dev/world-data/towns_discovery.lua")
[void]$builder.AppendLine("OMW_TOWNS_DISCOVERY_BUILD = {")
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine(('  gitCommit = "{0}",' -f $gitCommit))
[void]$builder.AppendLine('  stageId = "TOWNS_DISCOVERY_01",')
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("")
[void]$builder.AppendLine($configSource)

if ($PSBoundParameters.ContainsKey("TownsFile") -and -not [string]::IsNullOrWhiteSpace($TownsFile)) {
  $resolvedTownsFile = [System.IO.Path]::GetFullPath($TownsFile)
  $luaTownsFile = ConvertTo-LuaLongString -Value $resolvedTownsFile
  [void]$builder.AppendLine("")
  [void]$builder.AppendLine("-- Build-time override supplied through -TownsFile.")
  [void]$builder.AppendLine("OMW_TOWNS_DISCOVERY_CONFIG.townsFile = $luaTownsFile")
}

[void]$builder.AppendLine("")
[void]$builder.AppendLine($discoverySource)
[void]$builder.AppendLine("")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText(
  $outputPath,
  $builder.ToString().Replace("`r`n", "`n"),
  $utf8WithoutBom
)

Write-Output "Built TOWNS discovery bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
Write-Output "Git commit: $gitCommit"
if ($PSBoundParameters.ContainsKey("TownsFile") -and -not [string]::IsNullOrWhiteSpace($TownsFile)) {
  Write-Output "Embedded towns.lua path: $resolvedTownsFile"
} else {
  Write-Output "Embedded towns.lua path: automatic discovery"
}
