[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$w1SourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w1.lua"
$w2ConfigPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/config-tm02w2.lua"
$w2SourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/dist/TM02W2.lua"

function Get-NormalizedSource {
  param([Parameter(Mandatory = $true)][string]$Path)
  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

$w1SourceContent = Get-NormalizedSource -Path $w1SourcePath
$w2ConfigContent = Get-NormalizedSource -Path $w2ConfigPath
$w2SourceContent = Get-NormalizedSource -Path $w2SourcePath
$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm02w2-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- TM02W2 reuses the validated TM02W1 registry module, then adds planner-only source/cost reservations.")
[void]$builder.AppendLine("local TM02W2Build = {")
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine('  stageId = "TM02W2",')
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("local TM02W2Config = (function()")
[void]$builder.AppendLine($w2ConfigContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W1 = (function()")
[void]$builder.AppendLine($w1SourceContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2 = (function()")
[void]$builder.AppendLine($w2SourceContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local registryOk, registryResult = pcall(function()")
[void]$builder.AppendLine("  return TM02W1.start(TM02W2Config.network, TM02W2Build)")
[void]$builder.AppendLine("end)")
[void]$builder.AppendLine("if not registryOk then")
[void]$builder.AppendLine('  env.info("[OMW][TM02W2] level=ERROR event=registry_bootstrap_uncaught_error reason=" .. tostring(registryResult))')
[void]$builder.AppendLine("else")
[void]$builder.AppendLine("  local plannerOk, plannerResult = pcall(function()")
[void]$builder.AppendLine("    return TM02W2.start(TM02W2Config, registryResult, TM02W2Build)")
[void]$builder.AppendLine("  end)")
[void]$builder.AppendLine("  if not plannerOk then")
[void]$builder.AppendLine('    env.info("[OMW][TM02W2] level=ERROR event=planner_bootstrap_uncaught_error reason=" .. tostring(plannerResult))')
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("end")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)
Write-Output "Built TM02W2 bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
