[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$w1SourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w1.lua"
$w2ConfigPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/config-tm02w2.lua"
$w2SourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2.lua"
$w2eConfigPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/config-tm02w2e.lua"
$w2eAdapterPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2e-leader-proxy-adapter.lua"
$w2eNavigationPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2e-moose-navigation.lua"
$w2eSourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2e.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/dist/TM02W2E.lua"

function Get-NormalizedSource {
  param([Parameter(Mandatory = $true)][string]$Path)
  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

$w1SourceContent = Get-NormalizedSource -Path $w1SourcePath
$w2ConfigContent = Get-NormalizedSource -Path $w2ConfigPath
$w2SourceContent = Get-NormalizedSource -Path $w2SourcePath
$w2eConfigContent = Get-NormalizedSource -Path $w2eConfigPath
$w2eAdapterContent = Get-NormalizedSource -Path $w2eAdapterPath
$w2eNavigationContent = Get-NormalizedSource -Path $w2eNavigationPath
$w2eSourceContent = Get-NormalizedSource -Path $w2eSourcePath
$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm02w2e-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- Load vendor/moose/Moose.lua before this bundle.")
[void]$builder.AppendLine("local TM02W2EBuild = {")
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine('  stageId = "TM02W2E",')
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("local TM02W2PlannerConfig = (function()")
[void]$builder.AppendLine($w2ConfigContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2EConfig = (function()")
[void]$builder.AppendLine($w2eConfigContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("TM02W2PlannerConfig.mission.fileName = TM02W2EConfig.mission.fileName")
[void]$builder.AppendLine("TM02W2PlannerConfig.mission.displayName = TM02W2EConfig.mission.displayName")
[void]$builder.AppendLine("TM02W2PlannerConfig.network.mission.fileName = TM02W2EConfig.mission.fileName")
[void]$builder.AppendLine("TM02W2PlannerConfig.network.mission.displayName = TM02W2EConfig.mission.displayName")
[void]$builder.AppendLine("TM02W2PlannerConfig.debug.showMessages = false")
[void]$builder.AppendLine("TM02W2PlannerConfig.debug.enableF10Menu = false")
[void]$builder.AppendLine("TM02W2PlannerConfig.network.debug.showMessages = false")
[void]$builder.AppendLine("TM02W2PlannerConfig.network.debug.enableF10Menu = false")
[void]$builder.AppendLine("local TM02W1 = (function()")
[void]$builder.AppendLine($w1SourceContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2 = (function()")
[void]$builder.AppendLine($w2SourceContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2ELeaderProxyAdapter = (function()")
[void]$builder.AppendLine($w2eAdapterContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2EMooseNavigation = (function()")
[void]$builder.AppendLine($w2eNavigationContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2E = (function()")
[void]$builder.AppendLine($w2eSourceContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local bootstrapOk, bootstrapError = pcall(function()")
[void]$builder.AppendLine("  local registry = TM02W1.start(TM02W2PlannerConfig.network, TM02W2EBuild)")
[void]$builder.AppendLine("  if registry.configurationValid ~= true then")
[void]$builder.AppendLine('    error("TM02W1 registry validation failed")')
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("  local planner = TM02W2.start(TM02W2PlannerConfig, registry, TM02W2EBuild)")
[void]$builder.AppendLine("  if planner.configurationValid ~= true then")
[void]$builder.AppendLine('    error("TM02W2 planner validation failed")')
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("  TM02W2ELeaderProxyAdapter.install(TM02W2EConfig)")
[void]$builder.AppendLine("  local navigation = TM02W2EMooseNavigation.install(TM02W2EConfig, registry, planner)")
[void]$builder.AppendLine("  if navigation.valid ~= true then")
[void]$builder.AppendLine('    error("TM02W2E MOOSE navigation validation failed")')
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("  if navigation:preparePlannerTasks() ~= true then")
[void]$builder.AppendLine('    error("TM02W2E safe route planning failed")')
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("  local execution = TM02W2E.start(TM02W2EConfig, registry, planner, TM02W2EBuild)")
[void]$builder.AppendLine("  if execution.configurationValid ~= true then")
[void]$builder.AppendLine('    error("TM02W2E execution validation failed")')
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("  navigation:attach(execution)")
[void]$builder.AppendLine("  _G.OMW_TM02W2E_STATE = execution")
[void]$builder.AppendLine("  _G.OMW_TM02W2E_NAVIGATION = navigation")
[void]$builder.AppendLine("end)")
[void]$builder.AppendLine("if not bootstrapOk then")
[void]$builder.AppendLine('  env.info("[OMW][TM02W2E] level=ERROR event=execution_bootstrap_uncaught_error reason=" .. tostring(bootstrapError))')
[void]$builder.AppendLine("end")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)
Write-Output "Built TM02W2E bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
