[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$registrationSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\05-kandahar-dual-airwing-registration-preflight.lua'
$parkingSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\06-kandahar-dual-airwing-parking-contract-preflight.lua'
$calibrationSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\09-kandahar-uav-g-apron-calibration.lua'
$outputDir = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\dist'
$outputFile = Join-Path $outputDir 'OMW_AirOps_Kandahar_UAV_G_Apron_Calibration.lua'

foreach ($path in @($registrationSource, $parkingSource, $calibrationSource)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required source file not found: $path"
    }
}

$calibrationText = Get-Content -LiteralPath $calibrationSource -Raw

$requiredTokens = @(
    'CAL_AIR_US_KAF_UAV_G01',
    'CAL_AIR_US_KAF_UAV_G04',
    'CAL_AIR_US_KAF_UAV_G05',
    'CAL_AIR_US_KAF_UAV_G07',
    'CAL_AIR_US_KAF_UAV_G08',
    'CAL_AIR_US_KAF_UAV_G10',
    'CAL_AIR_US_KAF_UAV_G11',
    '_DATABASE:GetGroupTemplate',
    'GetParkingSpotsTable',
    'SQ_US_KAF_MQ1_361_ERS',
    'SQ_US_KAF_MQ9_361_ERS',
    ':SetParkingIDs(',
    'RESULT: PASS labels=7 mapped=7'
)

foreach ($token in $requiredTokens) {
    if ($calibrationText.IndexOf($token, [System.StringComparison]::Ordinal) -lt 0) {
        throw "Calibration source missing required token: $token"
    }
}

$forbiddenTokens = @(
    ':Start(',
    ':__Start(',
    'SPAWN:New',
    'AUFTRAG:New',
    'OPSTRANSPORT:New',
    'COMMANDER:New',
    'CHIEF:New',
    ':AddMission(',
    ':NewPayload(',
    ':Spawn(',
    'SetAllowSpawnOnClientParking'
)

foreach ($token in $forbiddenTokens) {
    if ($calibrationText.IndexOf($token, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "Calibration source contains forbidden runtime token: $token"
    }
}

$parts = @(
    '-- Generated by tools/build-kandahar-uav-g-apron-calibration.ps1',
    '-- BuilderVersion: KAF-UAV-G-APRON-CALIBRATION-1',
    '-- RuntimeBoundary: registration + parking contract + read-only marker calibration; no AIRWING start or spawn',
    (Get-Content -LiteralPath $registrationSource -Raw),
    (Get-Content -LiteralPath $parkingSource -Raw),
    $calibrationText
)

New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
$bundle = [string]::Join("`r`n`r`n", $parts)
[System.IO.File]::WriteAllText($outputFile, $bundle, [System.Text.UTF8Encoding]::new($false))

$luac = Get-Command luac -ErrorAction SilentlyContinue
if ($luac) {
    & $luac.Source -p $outputFile
    if ($LASTEXITCODE -ne 0) {
        throw "luac syntax validation failed for $outputFile"
    }
    Write-Host 'LuaSyntax: PASS'
}
else {
    Write-Host 'LuaSyntax: SKIPPED (luac not installed)'
}

Write-Host 'BuilderVersion: KAF-UAV-G-APRON-CALIBRATION-1'
Write-Host "Output: $outputFile"
Write-Host 'RequiredMarkerGroups: 7'
Write-Host 'MarkerLabels: G01,G04,G05,G07,G08,G10,G11'
Write-Host 'PreflightGuard: PASS'
Write-Host 'RuntimeBoundary: no AIRWING start, no spawn, no mission, no transport, no payload mutation'
