[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$registrationSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\05-kandahar-dual-airwing-registration-preflight.lua'
$parkingSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\06-kandahar-dual-airwing-parking-contract-preflight.lua'
$uavContractSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\10-kandahar-uav-fixed-parking-contract.lua'
$uavAssetSyncSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\10b-kandahar-uav-registered-asset-parking-sync.lua'
$controlledSpawnSource = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\src\11-kandahar-uav-controlled-spawn-test.lua'
$outputDir = Join-Path $repoRoot 'mission\tests\kandahar-air-operations\dist'
$outputFile = Join-Path $outputDir 'OMW_AirOps_Kandahar_UAV_Controlled_Spawn.lua'

foreach ($path in @($registrationSource, $parkingSource, $uavContractSource, $uavAssetSyncSource, $controlledSpawnSource)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required source file not found: $path"
    }
}

$uavContractText = Get-Content -LiteralPath $uavContractSource -Raw
$uavAssetSyncText = Get-Content -LiteralPath $uavAssetSyncSource -Raw
$controlledSpawnText = Get-Content -LiteralPath $controlledSpawnSource -Raw
$combinedTestText = $uavContractText + "`n" + $uavAssetSyncText + "`n" + $controlledSpawnText

$requiredTokens = @(
    'SQ_US_KAF_MQ1_361_ERS',
    'SQ_US_KAF_MQ9_361_ERS',
    'TPL_AIR_US_KAF_MQ1A_RECON_1SHIP',
    'TPL_AIR_US_KAF_MQ9_RECON_1SHIP',
    'G01',
    'G08',
    'G09',
    'G11',
    'TerminalID = 189',
    'TerminalID = 27',
    ':SetParkingIDs(',
    'asset.parkingIDs',
    'registeredAssetsSynchronized=true',
    ':AddRequest(',
    'WAREHOUSE.Descriptor.GROUPNAME',
    ':SetTakeoffCold(',
    ':Start(',
    'CASE_RESULT:',
    'RESULT: PASS cases=2 passed=2 failed=0'
)

foreach ($token in $requiredTokens) {
    if ($combinedTestText.IndexOf($token, [System.StringComparison]::Ordinal) -lt 0) {
        throw "UAV controlled-spawn source missing required token: $token"
    }
}

$forbiddenTokens = @(
    'SPAWN:New',
    'AUFTRAG:New',
    'OPSTRANSPORT:New',
    'COMMANDER:New',
    'CHIEF:New',
    ':AddMission(',
    ':NewPayload(',
    'SetAllowSpawnOnClientParking',
    'TaskRoute',
    'RouteTo',
    'CommandStart'
)

foreach ($token in $forbiddenTokens) {
    if ($combinedTestText.IndexOf($token, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "UAV controlled-spawn source contains forbidden runtime token: $token"
    }
}

$parts = @(
    '-- Generated by tools/build-kandahar-uav-controlled-spawn.ps1',
    '-- BuilderVersion: KAF-UAV-CONTROLLED-SPAWN-2',
    '-- RuntimeBoundary: fixed squadron parking contract + registered asset sync + one MQ-1 and one MQ-9 cold self-request',
    (Get-Content -LiteralPath $registrationSource -Raw),
    (Get-Content -LiteralPath $parkingSource -Raw),
    $uavContractText,
    $uavAssetSyncText,
    $controlledSpawnText
)

New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
$bundle = [string]::Join("`r`n`r`n", $parts)
[System.IO.File]::WriteAllText($outputFile, $bundle, [System.Text.UTF8Encoding]::new($false))

$luac = Get-Command luac -ErrorAction SilentlyContinue
if ($luac) {
    & $luac.Source -p $outputFile
    if ($LASTEXITCODE -ne 0) {
        throw "luac syntax validation failed for $outputFile"
    }
    Write-Host 'LuaSyntax: PASS'
}
else {
    Write-Host 'LuaSyntax: SKIPPED (luac not installed)'
}

Write-Host 'BuilderVersion: KAF-UAV-CONTROLLED-SPAWN-2'
Write-Host "Output: $outputFile"
Write-Host 'MQ1Pool: G01-G08 / 46,129,143,189,202,224,291,303 before runtime static filtering'
Write-Host 'MQ9Pool: G09-G11 / 27,54,263 before runtime static filtering'
Write-Host 'RegisteredAssetParkingSync: REQUIRED (4 MQ-1 asset groups + 2 MQ-9 asset groups)'
Write-Host 'ExpectedAssetGroups: 2'
Write-Host 'ExpectedUnits: 2'
Write-Host 'PreflightGuard: PASS'
Write-Host 'RuntimeBoundary: Main AIRWING only; one MQ-1 and one MQ-9; cold and uncontrolled; no AUFTRAG/OPSTRANSPORT/payload mutation/taxi/takeoff'
