[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$w1SourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w1.lua"
$basePlannerConfigPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/config-tm02w2.lua"
$w2fConfigPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/config-tm02w2f.lua"
$w2fPlannerPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2f-initial-fill-planner.lua"
$w2fBootstrapPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2f-bootstrap-menu.lua"
$leaderAdapterPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2e-leader-proxy-adapter.lua"
$directNavigationPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2f-direct-offroad-navigation.lua"
$combatEventsPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2e-combat-events-v3.lua"
$executorPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2e.lua"
$commanderSchedulerPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2f-commander-scheduler.lua"
$transitRepresentationPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2f-transit-representation-v9.lua"
$progressWatchdogPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w2f-progress-watchdog-v9.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/dist/TM02W2F.lua"

function Get-NormalizedSource {
  param([Parameter(Mandatory = $true)][string]$Path)
  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

$w1Source = Get-NormalizedSource -Path $w1SourcePath
$basePlannerConfig = Get-NormalizedSource -Path $basePlannerConfigPath
$w2fConfig = Get-NormalizedSource -Path $w2fConfigPath
$w2fPlanner = Get-NormalizedSource -Path $w2fPlannerPath
$w2fBootstrap = Get-NormalizedSource -Path $w2fBootstrapPath
$leaderAdapter = Get-NormalizedSource -Path $leaderAdapterPath
$directNavigation = Get-NormalizedSource -Path $directNavigationPath
$combatEvents = Get-NormalizedSource -Path $combatEventsPath
$executor = Get-NormalizedSource -Path $executorPath
$commanderScheduler = Get-NormalizedSource -Path $commanderSchedulerPath
$transitRepresentation = Get-NormalizedSource -Path $transitRepresentationPath
$progressWatchdog = Get-NormalizedSource -Path $progressWatchdogPath

$terminalGateOriginal = "local remaining = projection.totalMeters - projection.alongMeters"
$terminalGateReplacement = "local remaining = distance2D(group:GetCoordinate(), context.target)"
$terminalGateMatchCount = [regex]::Matches(
  $progressWatchdog,
  [regex]::Escape($terminalGateOriginal)
).Count
if ($terminalGateMatchCount -ne 1) {
  throw "Expected exactly one route-projection terminal gate in watchdog source, found $terminalGateMatchCount"
}
$progressWatchdog = $progressWatchdog.Replace($terminalGateOriginal, $terminalGateReplacement)

$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm02w2f-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- Load vendor/moose/Moose.lua before this bundle.")
[void]$builder.AppendLine("local TM02W2FBuild = {")
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine('  stageId = "TM02W2F",')
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("local TM02W2BaseConfig = (function()")
[void]$builder.AppendLine($basePlannerConfig)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2FConfig = (function()")
[void]$builder.AppendLine($w2fConfig)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("TM02W2BaseConfig.network.mission.fileName = TM02W2FConfig.mission.fileName")
[void]$builder.AppendLine("TM02W2BaseConfig.network.mission.displayName = TM02W2FConfig.mission.displayName")
[void]$builder.AppendLine("TM02W2BaseConfig.network.debug.showMessages = false")
[void]$builder.AppendLine("TM02W2BaseConfig.network.debug.enableF10Menu = false")
[void]$builder.AppendLine("local TM02W1 = (function()")
[void]$builder.AppendLine($w1Source)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2FInitialFillPlanner = (function()")
[void]$builder.AppendLine($w2fPlanner)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2FBootstrapMenu = (function()")
[void]$builder.AppendLine($w2fBootstrap)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2ELeaderProxyAdapter = (function()")
[void]$builder.AppendLine($leaderAdapter)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2FDirectOffroadNavigation = (function()")
[void]$builder.AppendLine($directNavigation)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2ECombatEventsV3 = (function()")
[void]$builder.AppendLine($combatEvents)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2E = (function()")
[void]$builder.AppendLine($executor)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2FCommanderScheduler = (function()")
[void]$builder.AppendLine($commanderScheduler)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2FTransitRepresentation = (function()")
[void]$builder.AppendLine($transitRepresentation)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W2FProgressWatchdog = (function()")
[void]$builder.AppendLine($progressWatchdog)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local bootstrapMenu = TM02W2FBootstrapMenu.install(TM02W2FConfig, TM02W2FBuild)")
[void]$builder.AppendLine("local bootstrapOk, bootstrapError = pcall(function()")
[void]$builder.AppendLine("  bootstrapMenu:update({ phase = 'REGISTRY', detail = 'validating all eleven RED network nodes' })")
[void]$builder.AppendLine("  local registry = TM02W1.start(TM02W2BaseConfig.network, TM02W2FBuild)")
[void]$builder.AppendLine("  if registry.configurationValid ~= true then error('TM02W1 registry validation failed') end")
[void]$builder.AppendLine("  bootstrapMenu:update({ phase = 'PLANNER', detail = 'creating minimum-packet initial fill plan' })")
[void]$builder.AppendLine("  local planner = TM02W2FInitialFillPlanner.start(TM02W2FConfig, TM02W2BaseConfig, registry, TM02W2FBuild)")
[void]$builder.AppendLine("  if planner.configurationValid ~= true then error('TM02W2F initial fill planner validation failed') end")
[void]$builder.AppendLine("  TM02W2ELeaderProxyAdapter.install(TM02W2FConfig)")
[void]$builder.AppendLine("  bootstrapMenu:update({ phase = 'NAVIGATION', detail = 'selecting strategic RED-network paths for direct off-road legs' })")
[void]$builder.AppendLine("  local navigation = TM02W2FDirectOffroadNavigation.install(TM02W2FConfig, registry, planner)")
[void]$builder.AppendLine("  local routingReady = navigation.valid == true and navigation:preparePlannerTasks() == true")
[void]$builder.AppendLine("  bootstrapMenu:update({")
[void]$builder.AppendLine("    phase = routingReady and 'EXECUTOR' or 'BLOCKED',")
[void]$builder.AppendLine("    detail = routingReady and 'creating direct off-road executor with exposure-guarded recovery' or 'safe direct off-road network path missing',")
[void]$builder.AppendLine("    navigationValid = navigation.valid == true,")
[void]$builder.AppendLine("    routingReady = routingReady,")
[void]$builder.AppendLine("    errorCount = #navigation.errors,")
[void]$builder.AppendLine("    warningCount = #navigation.warnings,")
[void]$builder.AppendLine("  })")
[void]$builder.AppendLine("  if routingReady ~= true then")
[void]$builder.AppendLine("    _G.OMW_TM02W2F_NAVIGATION = navigation")
[void]$builder.AppendLine("    return")
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("  TM02W2FConfig.debug.enableF10Menu = false")
[void]$builder.AppendLine("  local execution = TM02W2E.start(TM02W2FConfig, registry, planner, TM02W2FBuild)")
[void]$builder.AppendLine("  if execution.configurationValid ~= true then error('TM02W2F execution validation failed') end")
[void]$builder.AppendLine("  local commander = TM02W2FCommanderScheduler.install(TM02W2FConfig, execution, navigation, planner)")
[void]$builder.AppendLine("  if commander.valid ~= true then error('TM02W2F commander scheduler validation failed') end")
[void]$builder.AppendLine("  local combatEvents = TM02W2ECombatEventsV3.install(TM02W2FConfig, execution)")
[void]$builder.AppendLine("  if combatEvents.valid ~= true then error('TM02W2F combat event guard validation failed') end")
[void]$builder.AppendLine("  local transitRepresentation = TM02W2FTransitRepresentation.install(TM02W2FConfig, execution, navigation)")
[void]$builder.AppendLine("  if transitRepresentation.valid ~= true then error('TM02W2F transit representation validation failed') end")
[void]$builder.AppendLine("  local progressWatchdog = TM02W2FProgressWatchdog.install(TM02W2FConfig, execution, navigation)")
[void]$builder.AppendLine("  if progressWatchdog.valid ~= true then error('TM02W2F progress watchdog validation failed') end")
[void]$builder.AppendLine("  bootstrapMenu:update({")
[void]$builder.AppendLine("    phase = 'READY',")
[void]$builder.AppendLine("    detail = 'direct off-road commander and exposure-guarded watchdog 9 are ready',")
[void]$builder.AppendLine("    navigationValid = true,")
[void]$builder.AppendLine("    routingReady = true,")
[void]$builder.AppendLine("    executionReady = true,")
[void]$builder.AppendLine("    errorCount = #navigation.errors + #commander.errors + #transitRepresentation.errors + #progressWatchdog.errors,")
[void]$builder.AppendLine("    warningCount = #navigation.warnings + #planner.warnings + #progressWatchdog.warnings,")
[void]$builder.AppendLine("  })")
[void]$builder.AppendLine("  _G.OMW_TM02W2F_REGISTRY = registry")
[void]$builder.AppendLine("  _G.OMW_TM02W2F_PLANNER = planner")
[void]$builder.AppendLine("  _G.OMW_TM02W2F_STATE = execution")
[void]$builder.AppendLine("  _G.OMW_TM02W2F_NAVIGATION = navigation")
[void]$builder.AppendLine("  _G.OMW_TM02W2F_COMMANDER = commander")
[void]$builder.AppendLine("  _G.OMW_TM02W2F_TRANSIT_REPRESENTATION = transitRepresentation")
[void]$builder.AppendLine("  _G.OMW_TM02W2F_PROGRESS_WATCHDOG = progressWatchdog")
[void]$builder.AppendLine("  _G.OMW_TM02W2F_COMBAT_EVENTS = combatEvents")
[void]$builder.AppendLine("end)")
[void]$builder.AppendLine("if not bootstrapOk then")
[void]$builder.AppendLine("  bootstrapMenu:update({ phase = 'FAILED', detail = tostring(bootstrapError), executionReady = false })")
[void]$builder.AppendLine("  env.info('[OMW][TM02W2F] level=ERROR event=bootstrap_uncaught_error reason=' .. tostring(bootstrapError))")
[void]$builder.AppendLine("end")
[void]$builder.AppendLine("_G.OMW_TM02W2F_BOOTSTRAP = bootstrapMenu")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)
Write-Output "Built TM02W2F bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
