param()

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$campaignStatePath = Join-Path $root 'scripts\campaign\OMW_CampaignState.lua'
$harnessPath = Join-Path $root 'mission\tests\campaignstate-recovery-settlement\src\01-campaignstate-recovery-settlement.lua'
$outDir = Join-Path $root 'mission\tests\campaignstate-recovery-settlement\dist'
$outPath = Join-Path $outDir 'OMW_CampaignState_Recovery_Settlement.lua'

$builderVersion = 'CAMPAIGNSTATE-RECOVERY-SETTLEMENT-1'
$scope = 'CAMPAIGNSTATE_RECOVERY_SETTLEMENT'
$gitCommit = (git -C $root rev-parse HEAD).Trim()

$campaignState = Get-Content -LiteralPath $campaignStatePath -Raw
$harness = Get-Content -LiteralPath $harnessPath -Raw

$requiredCampaignMarkers = @(
  'function CampaignState.Restore(snapshot)',
  'function Store:CreditResourceOnce(spec)',
  'function Store:BeginAircraftRecovery(spec)',
  'function Store:CompleteAircraftRecovery(entityId, now)',
  'function Store:CompleteAircraftRepair(entityId, now)',
  'function Store:ExportSnapshot()'
)

foreach ($marker in $requiredCampaignMarkers) {
  if (-not $campaignState.Contains($marker)) {
    throw "CampaignState source is missing required marker: $marker"
  }
}

$forbidden = @(
  'STORAGE:',
  'WAREHOUSE:',
  'AIRWING:',
  'world.',
  'coalition.',
  'trigger.action',
  'io.',
  'lfs.',
  'os.execute',
  '_DATABASE'
)

foreach ($marker in $forbidden) {
  if ($campaignState.Contains($marker) -or $harness.Contains($marker)) {
    throw "Recovery settlement source contains forbidden runtime dependency: $marker"
  }
}

New-Item -ItemType Directory -Path $outDir -Force | Out-Null

$bundle = @"
-- Generated by tools/build-campaignstate-recovery-settlement.ps1
-- BuilderVersion: $builderVersion
-- Scope: $scope
-- GitCommit: $gitCommit

local function loadCampaignState()
  local chunk = function()
$campaignState
  end
  return chunk()
end

OMW_CampaignState = loadCampaignState()

$harness

OMW_CampaignState = nil
"@

Set-Content -LiteralPath $outPath -Value $bundle -Encoding UTF8
$hash = (Get-FileHash -LiteralPath $outPath -Algorithm SHA256).Hash.ToLowerInvariant()

Write-Host "Built: $outPath"
Write-Host "BuilderVersion: $builderVersion"
Write-Host "Scope: $scope"
Write-Host "CampaignStateAuthority: PRESENT"
Write-Host "RecoveryCreditIdempotency: PRESENT"
Write-Host "AircraftRecoveryState: PRESENT"
Write-Host "SnapshotRestore: PRESENT"
Write-Host "StorageMutation: ABSENT"
Write-Host "MOOSEDependency: ABSENT"
Write-Host "FilesystemIOInLua: ABSENT"
Write-Host "SHA256: $hash"
Write-Host "GitCommit: $gitCommit"
