[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$versionPath = Join-Path $repositoryRoot "vendor/moose/VERSION.md"
$moosePath = Join-Path $repositoryRoot "vendor/moose/Moose.lua"
$configPath = Join-Path $repositoryRoot "mission/tests/tm01-blue-convoy/config-tm01b.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm01-blue-convoy/dist/TM01B.lua"

function Get-MetadataValue {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Content,

    [Parameter(Mandatory = $true)]
    [string]$Pattern,

    [Parameter(Mandatory = $true)]
    [string]$Description
  )

  $match = [regex]::Match($Content, $Pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
  if (-not $match.Success) {
    throw "Could not read $Description."
  }

  return $match.Groups[1].Value.Trim()
}

function Get-NormalizedSource {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

function Add-Module {
  param(
    [Parameter(Mandatory = $true)]
    [System.Text.StringBuilder]$Builder,

    [Parameter(Mandatory = $true)]
    [string]$VariableName,

    [Parameter(Mandatory = $true)]
    [string]$RelativePath
  )

  $sourcePath = Join-Path $repositoryRoot $RelativePath
  if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
    throw "Required source module is missing: $RelativePath"
  }

  [void]$Builder.AppendLine("local $VariableName = (function()")
  [void]$Builder.AppendLine((Get-NormalizedSource -Path $sourcePath))
  [void]$Builder.AppendLine("end)()")
  [void]$Builder.AppendLine()
}

$versionContent = [System.IO.File]::ReadAllText($versionPath)
$expectedMooseVersion = Get-MetadataValue -Content $versionContent -Pattern '^Version:\s*(\S+)\s*$' -Description "MOOSE version"
$expectedHash = (Get-MetadataValue -Content $versionContent -Pattern '^SHA-256 Moose\.lua:\s*([0-9a-fA-F]{64})\s*$' -Description "expected Moose.lua SHA-256").ToLowerInvariant()
$expectedMooseBuildCommit = Get-MetadataValue -Content $versionContent -Pattern '^Embedded build commit:\s*([0-9a-fA-F]{40})\s*$' -Description "embedded MOOSE build commit"
$expectedMooseBuildTimestamp = Get-MetadataValue -Content $versionContent -Pattern '^Embedded build timestamp:\s*(\S+)\s*$' -Description "embedded MOOSE build timestamp"
$selectedRuntimeFile = Get-MetadataValue -Content $versionContent -Pattern '^Selected runtime file:\s*(\S+)\s*$' -Description "selected MOOSE runtime file"
$includeFamily = Get-MetadataValue -Content $versionContent -Pattern '^Include family:\s*(\S+)\s*$' -Description "MOOSE include family"
$compression = Get-MetadataValue -Content $versionContent -Pattern '^Compression:\s*(\S+)\s*$' -Description "MOOSE compression setting"

if ($selectedRuntimeFile -cne "Moose.lua") {
  throw "Unsupported selected MOOSE runtime file '$selectedRuntimeFile'; expected exact filename Moose.lua."
}

$actualHash = (Get-FileHash -LiteralPath $moosePath -Algorithm SHA256).Hash.ToLowerInvariant()
if ($actualHash -cne $expectedHash) {
  throw "MOOSE SHA-256 mismatch. Expected $expectedHash but found $actualHash."
}

$configContent = [System.IO.File]::ReadAllText($configPath)
$configurationVersion = Get-MetadataValue -Content $configContent -Pattern '^\s*configurationVersion\s*=\s*"([^"]+)"\s*,' -Description "TM01B configuration version"
$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm01b-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- Load vendor/moose/Moose.lua before this bundle.")
[void]$builder.AppendLine("local OMWBuild = {")
[void]$builder.AppendLine('  testId = "TM01",')
[void]$builder.AppendLine('  stageId = "TM01B",')
[void]$builder.AppendLine(('  configurationVersion = "{0}",' -f $configurationVersion))
[void]$builder.AppendLine(('  expectedMooseVersion = "{0}",' -f $expectedMooseVersion))
[void]$builder.AppendLine(('  expectedMooseFileSha256 = "{0}",' -f $expectedHash))
[void]$builder.AppendLine(('  expectedMooseBuildCommit = "{0}",' -f $expectedMooseBuildCommit))
[void]$builder.AppendLine(('  expectedMooseBuildTimestamp = "{0}",' -f $expectedMooseBuildTimestamp))
[void]$builder.AppendLine(('  expectedMooseIncludeFamily = "{0}",' -f $includeFamily))
[void]$builder.AppendLine(('  expectedMooseCompression = "{0}",' -f $compression))
[void]$builder.AppendLine('  mooseVerificationMode = "BUILD_HASH_PLUS_RUNTIME_API_CHECK",')
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine("}")
[void]$builder.AppendLine()

Add-Module -Builder $builder -VariableName "TM01BConfig" -RelativePath "mission/tests/tm01-blue-convoy/config-tm01b.lua"
Add-Module -Builder $builder -VariableName "SafeReporter" -RelativePath "mission/tests/common/src/safe_reporter.lua"
Add-Module -Builder $builder -VariableName "StructuredLogger" -RelativePath "mission/tests/common/src/structured_logger.lua"
Add-Module -Builder $builder -VariableName "RuntimeGuard" -RelativePath "mission/tests/common/src/runtime_guard.lua"
Add-Module -Builder $builder -VariableName "InMemoryCampaignState" -RelativePath "mission/tests/tm01-blue-convoy/src/in_memory_campaign_state.lua"
Add-Module -Builder $builder -VariableName "ConvoyCacheController" -RelativePath "mission/tests/tm01-blue-convoy/src/convoy_cache_controller.lua"
Add-Module -Builder $builder -VariableName "TM01B" -RelativePath "mission/tests/tm01-blue-convoy/src/tm01b.lua"

[void]$builder.AppendLine("local entryOk, entryResult = pcall(function()")
[void]$builder.AppendLine("  return TM01B.start({")
[void]$builder.AppendLine("    build = OMWBuild,")
[void]$builder.AppendLine("    config = TM01BConfig,")
[void]$builder.AppendLine("    safeReporter = SafeReporter,")
[void]$builder.AppendLine("    structuredLogger = StructuredLogger,")
[void]$builder.AppendLine("    runtimeGuard = RuntimeGuard,")
[void]$builder.AppendLine("    inMemoryCampaignState = InMemoryCampaignState,")
[void]$builder.AppendLine("    convoyCacheController = ConvoyCacheController,")
[void]$builder.AppendLine("  })")
[void]$builder.AppendLine("end)")
[void]$builder.AppendLine()
[void]$builder.AppendLine("local TM01BState = entryResult")
[void]$builder.AppendLine("if not entryOk then")
[void]$builder.AppendLine('  SafeReporter.report("bootstrap_uncaught_error", "FAIL_SCRIPT", entryResult, "[OMW][TM01B]")')
[void]$builder.AppendLine("  TM01BState = {")
[void]$builder.AppendLine('    outcome = "FAIL_SCRIPT",')
[void]$builder.AppendLine('    detail = "bootstrap raised an uncaught error",')
[void]$builder.AppendLine("  }")
[void]$builder.AppendLine("end")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)

Write-Output "Verified Moose.lua SHA-256: $actualHash"
Write-Output "Built TM01B bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"