[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/config-tm02w1.lua"
$sourcePath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/src/tm02w1.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm02-red-network/dist/TM02W1.lua"

function Get-NormalizedSource {
  param([Parameter(Mandatory = $true)][string]$Path)
  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

$configContent = Get-NormalizedSource -Path $configPath
$sourceContent = Get-NormalizedSource -Path $sourcePath
$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm02w1-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- TM02W1 uses the native DCS mission table. MOOSE may remain loaded for project consistency.")
[void]$builder.AppendLine("local TM02W1Build = {")
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine('  stageId = "TM02W1",')
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("local TM02W1Config = (function()")
[void]$builder.AppendLine($configContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local TM02W1 = (function()")
[void]$builder.AppendLine($sourceContent)
[void]$builder.AppendLine("end)()")
[void]$builder.AppendLine("local ok, result = pcall(function()")
[void]$builder.AppendLine("  return TM02W1.start(TM02W1Config, TM02W1Build)")
[void]$builder.AppendLine("end)")
[void]$builder.AppendLine("if not ok then")
[void]$builder.AppendLine('  env.info("[OMW][TM02W1] level=ERROR event=bootstrap_uncaught_error reason=" .. tostring(result))')
[void]$builder.AppendLine("end")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)
Write-Output "Built TM02W1 bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
