[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$versionPath = Join-Path $repositoryRoot "vendor/moose/VERSION.md"
$moosePath = Join-Path $repositoryRoot "vendor/moose/Moose.lua"
$configPath = Join-Path $repositoryRoot "mission/tests/tm01-blue-convoy/config-tm01c.lua"
$outputPath = Join-Path $repositoryRoot "mission/tests/tm01-blue-convoy/dist/TM01C.lua"

function Get-MetadataValue {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Content,
    [Parameter(Mandatory = $true)]
    [string]$Pattern,
    [Parameter(Mandatory = $true)]
    [string]$Description
  )

  $match = [regex]::Match($Content, $Pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
  if (-not $match.Success) {
    throw "Could not read $Description."
  }
  return $match.Groups[1].Value.Trim()
}

function Get-NormalizedSource {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )
  $content = [System.IO.File]::ReadAllText($Path)
  return ($content -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
}

function Add-Module {
  param(
    [Parameter(Mandatory = $true)]
    [System.Text.StringBuilder]$Builder,
    [Parameter(Mandatory = $true)]
    [string]$VariableName,
    [Parameter(Mandatory = $true)]
    [string]$RelativePath
  )

  $sourcePath = Join-Path $repositoryRoot $RelativePath
  if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
    throw "Required source module is missing: $RelativePath"
  }
  [void]$Builder.AppendLine("local $VariableName = (function()")
  [void]$Builder.AppendLine((Get-NormalizedSource -Path $sourcePath))
  [void]$Builder.AppendLine("end)()")
  [void]$Builder.AppendLine()
}

function Add-CompositeModule {
  param(
    [Parameter(Mandatory = $true)]
    [System.Text.StringBuilder]$Builder,
    [Parameter(Mandatory = $true)]
    [string]$VariableName,
    [Parameter(Mandatory = $true)]
    [string[]]$RelativePaths
  )

  [void]$Builder.AppendLine("local $VariableName = (function()")
  foreach ($relativePath in $RelativePaths) {
    $sourcePath = Join-Path $repositoryRoot $relativePath
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
      throw "Required source fragment is missing: $relativePath"
    }
    [void]$Builder.AppendLine((Get-NormalizedSource -Path $sourcePath))
  }
  [void]$Builder.AppendLine("end)()")
  [void]$Builder.AppendLine()
}

$versionContent = [System.IO.File]::ReadAllText($versionPath)
$expectedMooseVersion = Get-MetadataValue -Content $versionContent -Pattern '^Version:\s*(\S+)\s*$' -Description "MOOSE version"
$expectedHash = (Get-MetadataValue -Content $versionContent -Pattern '^SHA-256 Moose\.lua:\s*([0-9a-fA-F]{64})\s*$' -Description "expected Moose.lua SHA-256").ToLowerInvariant()
$expectedMooseBuildCommit = Get-MetadataValue -Content $versionContent -Pattern '^Embedded build commit:\s*([0-9a-fA-F]{40})\s*$' -Description "embedded MOOSE build commit"
$expectedMooseBuildTimestamp = Get-MetadataValue -Content $versionContent -Pattern '^Embedded build timestamp:\s*(\S+)\s*$' -Description "embedded MOOSE build timestamp"
$selectedRuntimeFile = Get-MetadataValue -Content $versionContent -Pattern '^Selected runtime file:\s*(\S+)\s*$' -Description "selected MOOSE runtime file"
$includeFamily = Get-MetadataValue -Content $versionContent -Pattern '^Include family:\s*(\S+)\s*$' -Description "MOOSE include family"
$compression = Get-MetadataValue -Content $versionContent -Pattern '^Compression:\s*(\S+)\s*$' -Description "MOOSE compression setting"

if ($selectedRuntimeFile -cne "Moose.lua") {
  throw "Unsupported selected MOOSE runtime file '$selectedRuntimeFile'; expected exact filename Moose.lua."
}

$actualHash = (Get-FileHash -LiteralPath $moosePath -Algorithm SHA256).Hash.ToLowerInvariant()
if ($actualHash -cne $expectedHash) {
  throw "MOOSE SHA-256 mismatch. Expected $expectedHash but found $actualHash."
}

$configContent = [System.IO.File]::ReadAllText($configPath)
$configurationVersion = Get-MetadataValue -Content $configContent -Pattern '^\s*configurationVersion\s*=\s*"([^"]+)"\s*,' -Description "TM01C configuration version"
$buildTimestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", [Globalization.CultureInfo]::InvariantCulture)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- Generated by tools/build-tm01c-bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("-- Load vendor/moose/Moose.lua before this bundle.")
[void]$builder.AppendLine("local OMWBuild = {")
[void]$builder.AppendLine('  testId = "TM01",')
[void]$builder.AppendLine('  stageId = "TM01C",')
[void]$builder.AppendLine(('  configurationVersion = "{0}",' -f $configurationVersion))
[void]$builder.AppendLine(('  expectedMooseVersion = "{0}",' -f $expectedMooseVersion))
[void]$builder.AppendLine(('  expectedMooseFileSha256 = "{0}",' -f $expectedHash))
[void]$builder.AppendLine(('  expectedMooseBuildCommit = "{0}",' -f $expectedMooseBuildCommit))
[void]$builder.AppendLine(('  expectedMooseBuildTimestamp = "{0}",' -f $expectedMooseBuildTimestamp))
[void]$builder.AppendLine(('  expectedMooseIncludeFamily = "{0}",' -f $includeFamily))
[void]$builder.AppendLine(('  expectedMooseCompression = "{0}",' -f $compression))
[void]$builder.AppendLine('  mooseVerificationMode = "BUILD_HASH_PLUS_RUNTIME_API_CHECK",')
[void]$builder.AppendLine(('  buildTimestamp = "{0}",' -f $buildTimestamp))
[void]$builder.AppendLine("}")
[void]$builder.AppendLine()

Add-Module -Builder $builder -VariableName "TM01CConfig" -RelativePath "mission/tests/tm01-blue-convoy/config-tm01c.lua"
Add-Module -Builder $builder -VariableName "SafeReporter" -RelativePath "mission/tests/common/src/safe_reporter.lua"
Add-Module -Builder $builder -VariableName "StructuredLogger" -RelativePath "mission/tests/common/src/structured_logger.lua"
Add-Module -Builder $builder -VariableName "RuntimeGuard" -RelativePath "mission/tests/common/src/runtime_guard.lua"
Add-Module -Builder $builder -VariableName "ProxyCampaignState" -RelativePath "mission/tests/tm01-blue-convoy/src/proxy_campaign_state.lua"
Add-Module -Builder $builder -VariableName "PlayerInterestMonitor" -RelativePath "mission/tests/tm01-blue-convoy/src/player_interest_monitor.lua"
Add-CompositeModule -Builder $builder -VariableName "ConvoyProxyController" -RelativePaths @(
  "mission/tests/tm01-blue-convoy/src/convoy_proxy_controller/01-core.lua",
  "mission/tests/tm01-blue-convoy/src/convoy_proxy_controller/02-road-spawn.lua",
  "mission/tests/tm01-blue-convoy/src/convoy_proxy_controller/02b-reduced-template-spawn.lua",
  "mission/tests/tm01-blue-convoy/src/convoy_proxy_controller/03-state-transitions.lua",
  "mission/tests/tm01-blue-convoy/src/convoy_proxy_controller/03b-rollback-cleanup.lua",
  "mission/tests/tm01-blue-convoy/src/convoy_proxy_controller/03c-damage-state.lua",
  "mission/tests/tm01-blue-convoy/src/convoy_proxy_controller/03d-route-activation.lua",
  "mission/tests/tm01-blue-convoy/src/convoy_proxy_controller/04-commands-runtime.lua"
)
Add-Module -Builder $builder -VariableName "TM01C" -RelativePath "mission/tests/tm01-blue-convoy/src/tm01c.lua"

[void]$builder.AppendLine("local entryOk, entryResult = pcall(function()")
[void]$builder.AppendLine("  local state = TM01C.start({")
[void]$builder.AppendLine("    build = OMWBuild,")
[void]$builder.AppendLine("    config = TM01CConfig,")
[void]$builder.AppendLine("    safeReporter = SafeReporter,")
[void]$builder.AppendLine("    structuredLogger = StructuredLogger,")
[void]$builder.AppendLine("    runtimeGuard = RuntimeGuard,")
[void]$builder.AppendLine("    proxyCampaignState = ProxyCampaignState,")
[void]$builder.AppendLine("    convoyProxyController = ConvoyProxyController,")
[void]$builder.AppendLine("  })")
[void]$builder.AppendLine('  if type(state) == "table" and state.outcome == "READY" and type(state.proxyController) == "table" then')
[void]$builder.AppendLine("    local monitorOk, monitorOrError = pcall(function()")
[void]$builder.AppendLine("      return PlayerInterestMonitor.attach({")
[void]$builder.AppendLine("        controller = state.proxyController,")
[void]$builder.AppendLine("        config = TM01CConfig,")
[void]$builder.AppendLine('        logger = StructuredLogger.new("[OMW][TM01C]"),')
[void]$builder.AppendLine("        announce = function(text)")
[void]$builder.AppendLine('          trigger.action.outText("[OMW][TM01C] " .. text, 15, false)')
[void]$builder.AppendLine("        end,")
[void]$builder.AppendLine("      })")
[void]$builder.AppendLine("    end)")
[void]$builder.AppendLine('    if not monitorOk or type(monitorOrError) ~= "table" then')
[void]$builder.AppendLine('      state.outcome = "FAIL_SCRIPT"')
[void]$builder.AppendLine('      state.detail = "player interest monitor initialization failed"')
[void]$builder.AppendLine("      SafeReporter.report(")
[void]$builder.AppendLine('        "player_interest_monitor_initialization_failed",')
[void]$builder.AppendLine('        "FAIL_SCRIPT",')
[void]$builder.AppendLine('        monitorOk and "monitor factory returned no table" or monitorOrError,')
[void]$builder.AppendLine('        "[OMW][TM01C]"')
[void]$builder.AppendLine("      )")
[void]$builder.AppendLine("    else")
[void]$builder.AppendLine("      state.playerInterestMonitor = monitorOrError")
[void]$builder.AppendLine("    end")
[void]$builder.AppendLine("  end")
[void]$builder.AppendLine("  return state")
[void]$builder.AppendLine("end)")
[void]$builder.AppendLine()
[void]$builder.AppendLine("local TM01CState = entryResult")
[void]$builder.AppendLine("if not entryOk then")
[void]$builder.AppendLine('  SafeReporter.report("bootstrap_uncaught_error", "FAIL_SCRIPT", entryResult, "[OMW][TM01C]")')
[void]$builder.AppendLine("  TM01CState = {")
[void]$builder.AppendLine('    outcome = "FAIL_SCRIPT",')
[void]$builder.AppendLine('    detail = "bootstrap raised an uncaught error",')
[void]$builder.AppendLine("  }")
[void]$builder.AppendLine("end")

$outputDirectory = Split-Path -Parent $outputPath
[void](New-Item -ItemType Directory -Path $outputDirectory -Force)
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $builder.ToString().Replace("`r`n", "`n"), $utf8WithoutBom)

Write-Output "Verified Moose.lua SHA-256: $actualHash"
Write-Output "Built TM01C bundle: $outputPath"
Write-Output "Build timestamp: $buildTimestamp"
