local config = {
  configurationVersion = "TM02W2E-red-road-transit-watchdog-2",
  testId = "TM02",
  stageId = "TM02W2E",
  mission = {
    fileName = "OMW_TEST_TM02W2E_RED_TASK_EXECUTION.miz",
    displayName = "OMW TM02W2E - RED Road Transit and Watchdog",
  },
  templatesByStrength = {
    [1] = "TPL_TEST_RED_PACKET_01_01",
    [2] = "TPL_TEST_RED_PACKET_02_01",
    [3] = "TPL_TEST_RED_PACKET_03_01",
    [4] = "TPL_TEST_RED_PACKET_04_01",
    [5] = "TPL_TEST_RED_PACKET_05_01",
    [6] = "TPL_TEST_RED_PACKET_06_01",
    [7] = "TPL_TEST_RED_PACKET_07_01",
    [8] = "TPL_TEST_RED_PACKET_08_01",
    [9] = "TPL_TEST_RED_PACKET_09_01",
    [10] = "TPL_TEST_RED_PACKET_10_01",
  },
  proxy = {
    sourcePolicy = "LEADER_FROM_TASK_TEMPLATE",
    sourceUnitIndex = 1,
    runtimeAliasPrefix = "TM02W2E_RED_PROXY_",
    expectedUnitCount = 1,
    launchSlots = {
      { x = -15, y = -10 },
      { x = 0, y = -10 },
      { x = 15, y = -10 },
      { x = -15, y = 10 },
      { x = 0, y = 10 },
      { x = 15, y = 10 },
    },
  },
  physical = {
    runtimeAliasPrefix = "TM02W2E_RED_FULL_",
  },
  execution = {
    maxActiveTasks = 4,
    maxActiveOutboundPerSource = 1,
    monitorInitialDelaySeconds = 2,
    monitorIntervalSeconds = 2,
    autoStart = false,
  },
  routing = {
    proxyTestSpeedKph = 120,
    formation = "On Road",
    roadFormation = "On Road",
    assignmentDelaySeconds = 1,
  },
  navigation = {
    blueObjectiveBufferMeters = 250,
    maximumRoadSnapMeters = 1500,
    routeWaypointSpacingMeters = 100,
    portalArrivalRadiusMeters = 100,
    watchdogInitialDelaySeconds = 5,
    watchdogIntervalSeconds = 5,
    stuckWindowSeconds = 30,
    minimumTravelMeters = 8,
    minimumProgressMeters = 5,
    circularTravelMeters = 25,
    circularNetMeters = 8,
    combatCooldownSeconds = 90,
    recoveryAdvanceMeters = 20,
    maximumRecoveryAdvanceMeters = 80,
    maxRecoveryAttempts = 4,
  },
  debug = {
    showMessages = true,
    enableF10Menu = true,
    markersEnabledOnStart = true,
    markerIdBase = 220600,
  },
}
return config
